apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: markedb
    app.kubernetes.io/component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: markedb
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: markedb
        app.kubernetes.io/component: nginx
    spec:
      containers:
        - name: backend
          image: markedb-nginx
          ports:
            - containerPort: 8080
